all = [{'Site': 'Google Scholar1', 'Authors': 'A Bogdanchikov, M Zhaparov, R Suliyev', 'Title': 'Python to learn programming', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:UeHWp8X0CEIC', 'Year': '2013', 'Where published': 'Journal of Physics: Conference Series 423 (1)'},
{'Site': 'Google Scholar2', 'Authors': 'A Yedilkhan, S Rassim, B Andrey, N Ari', 'Title': 'Design of an information display based on several LED matrices and a single microcontroller', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:d1gkVwhDpl0C', 'Year': '2013', 'Where published': '2013 7th International Conference on Application of Information and\xa0…'},
{'Site': 'Google Scholar3', 'Authors': 'A Serek, A Issabek, A Bogdanchikov', 'Title': 'Distributed sentiment analysis of an agglutinative language via Spark by applying machine learning methods', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:ufrVoPGSRksC', 'Year': '2019', 'Where published': '2019 15th International Conference on Electronics'},
{'Site': 'Google Scholar4', 'Authors': 'A Bogdanchikov, D Kariboz, M Meraliyev', 'Title': 'Face extraction and recognition from public images using HIPI', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:eQOLeE2rZwMC', 'Year': '2019', 'Where published': '2018 14th International Conference on Electronics Computer and Computation\xa0…'},
{'Site': 'Google Scholar5', 'Authors': 'A Kaiyr, S Kadyrov, A Bogdanchikov', 'Title': 'Automatic Language Identification from Spectorgam Images', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:_FxGoFyzp5QC', 'Year': '2021', 'Where published': '2021 IEEE International Conference on Smart Information Systems and\xa0…'},
{'Site': 'Google Scholar6', 'Authors': 'BH Aitchanov, AB Satabaldiyev, AV Bogdanchikov, KN Latuta', 'Title': 'Innovative approach to social media in education', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:2osOgNQ5qMEC', 'Year': '2013', 'Where published': 'News of the National Academy of Sciences of the Republic of Kazakhstan\xa0…'},
{'Site': 'Google Scholar7', 'Authors': 'K Orynbekova, A Talasbek, A Omar, A Bogdanchikov, S Kadyrov', 'Title': 'MBTI personality classification using Apache Spark', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:LkGwnXOMwfcC', 'Year': '2021', 'Where published': '2021 16th International Conference on Electronics Computer and Computation\xa0…'},
{'Site': 'Google Scholar8', 'Authors': 'D Kariboz, A Bogdanchikov, K Orynbekova', 'Title': 'Computing feature vectors of students for face recognition using Apache Spark', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:WF5omc3nYNoC', 'Year': '2019', 'Where published': '2019 15th International Conference on Electronics'},
{'Site': 'Google Scholar9', 'Authors': 'A Bogdanchikov, R Suliyev, B Bolatov', 'Title': 'Implementing cycling training application for mobile devices', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:zYLM7Y9cAGgC', 'Year': '2016', 'Where published': '2016 IEEE 10th International Conference on Application of Information and\xa0…'},
{'Site': 'Google Scholar10', 'Authors': 'A Bogdanchikov, J Marshal', 'Title': 'Analisys of Kazakhstan satellite images by distributed system Hadoop', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:IjCSPb-OGe4C', 'Year': '2015', 'Where published': '2015 Twelve International Conference on Electronics Computer and Computation\xa0…'},
{'Site': 'Google Scholar11', 'Authors': 'YN Amirgaliyev, RN Suliyev, AV Bogdanchikov, KN Latuta, N Ari', 'Title': 'APPLICATION OF MICROCONTROLLER TO IMPLEMENT A DEVICE THAT CAN DISPLAY LONG MESSAGES ON LED MATRICES', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:YsMSGLbcyi4C', 'Year': '2013', 'Where published': 'BULLETIN OF THE NATIONAL ACADEMY OF SCIENCES OF THE REPUBLIC OF KAZAKHSTAN'},
{'Site': 'Google Scholar12', 'Authors': 'YN Amirgaliyev, A Kutlu, AV Bogdanchikov, KN Latuta, RN Suliyev', 'Title': 'USING ANDROID TO IMPLEMENT INTELLIGENT TESTING SYSTEM', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:qjMakFHDy7sC', 'Year': '2013', 'Where published': 'BULLETIN OF THE NATIONAL ACADEMY OF SCIENCES OF THE REPUBLIC OF KAZAKHSTAN\xa0…'},
{'Site': 'Google Scholar13', 'Authors': 'G Tulemissova, A Bogdanchikov, M Zhaparov, T Sunmonu, ...', 'Title': 'ICECCO2021 Reviewers', 'Link': 'https://scholar.google.com//citations?view_op=view_citation&hl=ru&user=6Ust3WUAAAAJ&citation_for_view=6Ust3WUAAAAJ:roLk4NBRz8UC', 'Year': '', 'Where published': ''},
{'Site': 'IEEE Xplore1', 'Authors': 'A. Kaiyr,S. Kadyrov,A. Bogdanchikov', 'Title': 'Automatic Language Identification from Spectorgam Images', 'Link': 'https://ieeexplore.ieee.org/document/9465996/', 'Year': '2021', 'Publisher': 'IEEE', 'Where published': '2021 IEEE International Conference on Smart Information Systems and Technologies (SIST)', 'PP.': '1 - 4', 'Volume': '1940'},
{'Site': 'IEEE Xplore2', 'Authors': 'A. Bogdanchikov,J. Marshal', 'Title': 'Analisys of Kazakhstan satellite images by distributed system Hadoop', 'Link': 'https://ieeexplore.ieee.org/document/7416871/', 'Year': '2015', 'Publisher': 'IEEE', 'Where published': '2015 Twelve International Conference on Electronics Computer and Computation (ICECCO)', 'PP.': '1 - 4', 'Volume': '830'},
{'Site': 'IEEE Xplore3', 'Authors': 'A. Bogdanchikov,R. Suliyev,B. Bolatov', 'Title': 'Implementing cycling training application for mobile devices', 'Link': 'https://ieeexplore.ieee.org/document/7991740/', 'Year': '2016', 'Publisher': 'IEEE', 'Where published': '2016 IEEE 10th International Conference on Application of Information and Communication Technologies (AICT)', 'PP.': '1 - 3', 'Volume': '340'},
{'Site': 'IEEE Xplore4', 'Authors': 'A. Serek,A. Issabek,A. Bogdanchikov', 'Title': 'Distributed sentiment analysis of an agglutinative language via Spark by applying machine learning methods', 'Link': 'https://ieeexplore.ieee.org/document/9043264/', 'Year': '2019', 'Publisher': 'IEEE', 'Where published': '2019 15th International Conference on Electronics, Computer and Computation (ICECCO)', 'PP.': '1 - 4', 'Volume': '175'},
{'Site': 'IEEE Xplore5', 'Authors': 'K. Orynbekova,A. Talasbek,A. Omar,A. Bogdanchikov,S. Kadyrov', 'Title': 'MBTI personality classification using Apache Spark', 'Link': 'https://ieeexplore.ieee.org/document/9663858/', 'Year': '2021', 'Publisher': 'IEEE', 'Where published': '2021 16th International Conference on Electronics Computer and Computation (ICECCO)', 'PP.': '1 - 4', 'Volume': '587'},
{'Site': 'IEEE Xplore6', 'Authors': 'A. Bogdanchikov,D. Kariboz,M. Meraliyev', 'Title': 'Face Extraction and Recognition from Public Images Using HIPI', 'Link': 'https://ieeexplore.ieee.org/document/8634718/', 'Year': '2018', 'Publisher': 'IEEE', 'Where published': '2018 14th International Conference on Electronics Computer and Computation (ICECCO)', 'PP.': '206 - 212', 'Volume': '275'},
{'Site': 'IEEE Xplore7', 'Authors': 'D. Kariboz,A. Bogdanchikov,K. Orynbekova', 'Title': 'Computing feature vectors of students for face recognition using Apache Spark', 'Link': 'https://ieeexplore.ieee.org/document/9043282/', 'Year': '2019', 'Publisher': 'IEEE', 'Where published': '2019 15th International Conference on Electronics, Computer and Computation (ICECCO)', 'PP.': '1 - 3', 'Volume': '156'},
{'Site': 'IEEE Xplore8', 'Authors': 'A. Yedilkhan,S. Rassim,B. Andrey,N. Ari', 'Title': 'Design of an information display based on several LED matrices and a single microcontroller', 'Link': 'https://ieeexplore.ieee.org/document/6722728/', 'Year': '2013', 'Publisher': 'IEEE', 'Where published': '2013 7th International Conference on Application of Information and Communication Technologies', 'PP.': '1 - 4', 'Volume': '440'}]
title = []
year = []
pub = []
print(len(all))
for item in all:
    title.append(item['Title'])
    year.append(item['Year'])
    pub.append(item['Where published'])
    
for i in all:
    print(i)
for i in range(len(title)):
    if title.count(title[i])>1:
        tit_i = title[i]
        a = i+1
        for j in range(i+1, len(title)):
            t = title[a]
            if t == tit_i and year[i] == year[a] and pub[i] == pub[a]:
                all.remove(j)
            else:
                a +=1
print(len(all))
